services:
  - type: web
    name: nota-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        generateValue: true
      - key: SUPABASE_ANON_KEY
        generateValue: true
